### ISSUE TITLE
Extra condition not usable

### ISSUE THREAD

**Issue by jullit31** [langestefan/auto-sun-blind#2]
The "Extra Conditions" section has a selector for actions:
![image](https://github.com/langestefan/auto-sun-blind/assets/19243986/503cb6c4-ea2a-4d27-8a61-842a4500b401)

**Comment by neskweek** [comment]
I confirm the issue. 
It can be corrected by changing  line 195 in file /homeassistant/blueprints/automation/langestefan/auto_sun_blind.yaml: 

        action: {}
by     

        condition: {}


and then reload/restart Home Assistant

**Comment by langestefan** [comment]
Closed by #4
